name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: pleijan/pleijan@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: 425e7379-9221-4629-b48d-51a93e1befa9
          GH_TOKEN: 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
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "en"
